version: '3'
services:

  db:
    image: postgres:latest
    restart: always
    volumes:
      - /db:/var/lib/postgresql
    environment:
      - POSTGRES_USER=tracuser
      - POSTGRES_PASSWORD=DevOps657
      - POSTGRES_DB=trac

  app:
    build: app/
    command: bash -c "trac-admin /project1 initenv trac postgres://tracuser:DevOps657@db/trac && tracd --port 80 /project1"
    ports: 
      - 80:80
    depends_on:
      - db