version: '3'
services:

  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=tracuser
      - POSTGRES_PASSWORD=DevOps657
      - POSTGRES_DB=trac

  app:
    build: app/
    links:
      - "db"
    command: ./app/deploy.sh
    ports: 
      - 80:80
    depends_on:
      - db