version: '3'
services:

  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=tracuser
      - POSTGRES_PASSWORD=DevOps657
      - POSTGRES_DB=trac

  app:
    build: app/
    ports: 
      - 80:80
    depends_on:
      - db